name: Create release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Lygia tag'
        required: false
        type: string

env:
  PACKAGE_JSON: "./package.json"
  PACKAGE_PATH: "."


jobs:        
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with: 
          repository: patriciogonzalezvivo/lygia
          fetch-tags: true
          ref: ${{ inputs.tag }}
      - run: |
          git fetch --unshallow --tags
          echo $?
          ls -la
          echo $PWD
      
      
      - name: Get package properties
        id: package_data
        uses: zoexx/github-action-json-file-properties@1.0.4
        with:
          file_path: "${{ env.PACKAGE_JSON }}"

      - name: Replace Author in package.json with proper object expected by vcc nuke
        run: jq '.author = {} | .author.name = "${{ steps.package_data.outputs.author }}" | .author.url = "https://patriciogonzalezvivo.com/" | .displayName = "${{ steps.package_data.outputs.name }}" | .licensesUrl = "https://lygia.xyz/license"' ${{ env.PACKAGE_JSON }}  > tmp && mv tmp ${{ env.PACKAGE_JSON }}
      
      - name: Create Package Zip
        working-directory: "${{ env.PACKAGE_PATH }}"
        run: zip -r "${{ steps.package_data.outputs.name }}-${{ steps.package_data.outputs.version }}.zip" . -x .git/* .github/*
      
      - name: Make Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: |
            ${{ steps.package_data.outputs.name }}-${{ steps.package_data.outputs.version }}.zip
            ${{ env.PACKAGE_JSON }}
            LICENSE.md
          tag_name: ${{ steps.package_data.outputs.version }}
