name: Create release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PACKAGE_JSON: "./package.json"
  PACKAGE_PATH: "."


jobs:        
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with: 
          repository: patriciogonzalezvivo/lygia
          fetch-tags: true
      - run: |
          git fetch --unshallow --tags
          echo $?
          ls -la
          echo $PWD
      
      
      - name: Get package properties
        id: package_data
        uses: zoexx/github-action-json-file-properties@1.0.4
        with:
          file_path: "${{ env.PACKAGE_JSON }}"
      
      - name: Create Package Zip
        working-directory: "${{ steps.package_data.outputs.version }}"
        run: zip -r "./${{ steps.package_data.outputs.name }}-${{ steps.package_data.outputs.version }}.zip" . -x .git .github

      - name: Create Tag
        id: create_tag
        uses: rickstaa/action-create-tag@88dbf7ff6fe2405f8e8f6c6fdfd78829bc631f83
        with:
          tag: ${{ steps.package_data.outputs.version }}
      
      - name: Make Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: |
            ${{ steps.package_data.outputs.name }}-${{ steps.package_data.outputs.version }}.zip
            ${{ env.PACKAGE_JSON }}
          tag_name: ${{ steps.package_data.outputs.version }}
