name: Create release

on:
  workflow_dispatch:
    inputs:
      latest:
        description: 'build using latest'
        required: true
        type: boolean
      tag:
        description: 'tag to build'
        required: false
        type: string

env:
  PACKAGE_JSON: "./package.json"
  PACKAGE_PATH: "."


jobs:        
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "patriciogonzalezvivo/lygia"
          latest: ${{ inputs.latest }}
          tag: ${{ inputs.tag }}
          tarBall: true
          extract: true
      
      
      - name: Get package properties
        id: package_data
        uses: zoexx/github-action-json-file-properties@1.0.4
        with:
          file_path: "${{ env.PACKAGE_JSON }}"

      - name: Replace Author in package.json with proper object expected by vcc nuke
        run: jq '.author = {} | .author.name = "${{ steps.package_data.outputs.author }}" | .displayName = "${{ steps.package_data.outputs.name }}"' ${{ env.PACKAGE_JSON }}  > tmp && mv tmp ${{ env.PACKAGE_JSON }}
      
      - name: Create Package Zip
        working-directory: "${{ env.PACKAGE_PATH }}"
        run: zip -r "${{ steps.package_data.outputs.name }}-${{ steps.package_data.outputs.version }}.zip" . -x .git/* .github/*

      - name: Create Tag
        id: create_tag
        uses: rickstaa/action-create-tag@88dbf7ff6fe2405f8e8f6c6fdfd78829bc631f83
        with:
          tag: ${{ steps.package_data.outputs.version }}
          tag_exists_error: false
      
      - name: Make Release
        if: ${{ steps.tag_create.outputs.tag_exists == false }}
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          files: |
            ${{ steps.package_data.outputs.name }}-${{ steps.package_data.outputs.version }}.zip
            ${{ env.PACKAGE_JSON }}
          tag_name: ${{ steps.package_data.outputs.version }}
